import { default as React } from '../../../node_modules/react';
import { TInputSizes } from './types';
export interface IInput {
    label?: string;
    helperLink?: string;
    disabled?: boolean;
    size: TInputSizes;
    helperText?: string;
    placeholder?: string;
    isRequired?: boolean;
    isOptional?: boolean;
    helpTextIcon?: React.FC;
    showPrefixIcon?: boolean;
    prefixIcon?: React.FC;
    prefixValue?: string;
    isValidated?: boolean;
    defaultValue?: string;
    shortcutKey?: string;
    suffixIcon?: React.FC;
    bankLogoIcon?: string;
    showSuffixButton?: boolean;
    showValidation?: boolean;
    isValid?: (value: any) => boolean;
    errorText?: string;
    successText?: string;
    onChange?: (value: any) => void;
    onFocus?: () => void;
    onBlur?: () => void;
    id?: string;
}
export declare const Input: ({ label, helperLink, helperText, disabled, placeholder, isRequired, isOptional, helpTextIcon, showPrefixIcon, prefixIcon, prefixValue, defaultValue, shortcutKey, suffixIcon, bankLogoIcon, showSuffixButton, showValidation, isValid, errorText, successText, onChange, onFocus, onBlur, size, id }: IInput) => import("react/jsx-runtime").JSX.Element;
