/** @type {import('tailwindcss').Config} */
module.exports = {
  content: [
    "./design-system-test/**/*.{js,ts,jsx,tsx}",
    "./src/**/*.{js,ts,jsx,tsx}",
    "./storybook-static/**/*.{js,ts,jsx,tsx}"
  ],
  theme: {
    extend: {
      colors: {
        // Plum Red
        'plumRed': {
          50: 'var(--color-plumRed-50)',
          100: 'var(--color-plumRed-100)',
          200: 'var(--color-plumRed-200)',
          300: 'var(--color-plumRed-300)',
          400: 'var(--color-plumRed-400)',
          500: 'var(--color-plumRed-500)',
          600: 'var(--color-plumRed-600)',
          700: 'var(--color-plumRed-700)',
          800: 'var(--color-plumRed-800)',
          900: 'var(--color-plumRed-900)',
          950: 'var(--color-plumRed-950)',
          'a50': 'var(--color-plumRed-a50)',
          'a100': 'var(--color-plumRed-a100)',
          'a150': 'var(--color-plumRed-a150)',
          'a200': 'var(--color-plumRed-a200)',
        },
        // Brand Purple
        'brandPurple': {
          50: 'var(--color-brandPurple-50)',
          100: 'var(--color-brandPurple-100)',
          200: 'var(--color-brandPurple-200)',
          300: 'var(--color-brandPurple-300)',
          400: 'var(--color-brandPurple-400)',
          500: 'var(--color-brandPurple-500)',
          600: 'var(--color-brandPurple-600)',
          700: 'var(--color-brandPurple-700)',
          800: 'var(--color-brandPurple-800)',
          900: 'var(--color-brandPurple-900)',
          950: 'var(--color-brandPurple-950)',
        },
        // Black with alpha variants
        'black': {
          500: 'var(--color-black-500)',
          'a10': 'var(--color-black-a10)',
          'a25': 'var(--color-black-a25)',
          'a50': 'var(--color-black-a50)',
          'a100': 'var(--color-black-a100)',
          'a200': 'var(--color-black-a200)',
          'a300': 'var(--color-black-a300)',
          'a400': 'var(--color-black-a400)',
          'a450': 'var(--color-black-a450)',
        },
        // Blue
        'blue': {
          50: 'var(--color-blue-50)',
          100: 'var(--color-blue-100)',
          200: 'var(--color-blue-200)',
          300: 'var(--color-blue-300)',
          400: 'var(--color-blue-400)',
          500: 'var(--color-blue-500)',
          600: 'var(--color-blue-600)',
          700: 'var(--color-blue-700)',
          800: 'var(--color-blue-800)',
          900: 'var(--color-blue-900)',
          950: 'var(--color-blue-950)',
          'a150': 'var(--color-blue-a150)',
        },
        // White with alpha variants
        'white': {
          500: 'var(--color-white-500)',
          'transparent': 'var(--color-white-transparent)',
          'a10': 'var(--color-white-a10)',
          'a25': 'var(--color-white-a25)',
          'a50': 'var(--color-white-a50)',
          'a100': 'var(--color-white-a100)',
          'a200': 'var(--color-white-a200)',
          'a300': 'var(--color-white-a300)',
          'a400': 'var(--color-white-a400)',
          'a450': 'var(--color-white-a450)',
        },
        // Red
        'red': {
          50: 'var(--color-red-50)',
          100: 'var(--color-red-100)',
          200: 'var(--color-red-200)',
          300: 'var(--color-red-300)',
          400: 'var(--color-red-400)',
          500: 'var(--color-red-500)',
          600: 'var(--color-red-600)',
          700: 'var(--color-red-700)',
          800: 'var(--color-red-800)',
          900: 'var(--color-red-900)',
          950: 'var(--color-red-950)',
          'a50': 'var(--color-red-a50)',
          'a100': 'var(--color-red-a100)',
          'a150': 'var(--color-red-a150)',
          'a200': 'var(--color-red-a200)',
        },
        // Green
        'green': {
          50: 'var(--color-green-50)',
          100: 'var(--color-green-100)',
          200: 'var(--color-green-200)',
          300: 'var(--color-green-300)',
          400: 'var(--color-green-400)',
          500: 'var(--color-green-500)',
          600: 'var(--color-green-600)',
          700: 'var(--color-green-700)',
          800: 'var(--color-green-800)',
          900: 'var(--color-green-900)',
          950: 'var(--color-green-950)',
        },
        // Gray with alpha variants
        'gray': {
          50: 'var(--color-gray-50)',
          100: 'var(--color-gray-100)',
          200: 'var(--color-gray-200)',
          300: 'var(--color-gray-300)',
          400: 'var(--color-gray-400)',
          500: 'var(--color-gray-500)',
          600: 'var(--color-gray-600)',
          700: 'var(--color-gray-700)',
          800: 'var(--color-gray-800)',
          900: 'var(--color-gray-900)',
          950: 'var(--color-gray-950)',
          'a25': 'var(--color-gray-a25)',
          'a50': 'var(--color-gray-a50)',
          'a75': 'var(--color-gray-a75)',
          'a100': 'var(--color-gray-a100)',
          'a150': 'var(--color-gray-a150)',
          'a200': 'var(--color-gray-a200)',
          'a400': 'var(--color-gray-a400)',
        },
        // Beige with alpha variants
        'beige': {
          50: 'var(--color-beige-50)',
          100: 'var(--color-beige-100)',
          200: 'var(--color-beige-200)',
          300: 'var(--color-beige-300)',
          400: 'var(--color-beige-400)',
          500: 'var(--color-beige-500)',
          600: 'var(--color-beige-600)',
          700: 'var(--color-beige-700)',
          800: 'var(--color-beige-800)',
          900: 'var(--color-beige-900)',
          950: 'var(--color-beige-950)',
          'a50': 'var(--color-beige-a50)',
          'a100': 'var(--color-beige-a100)',
          'a150': 'var(--color-beige-a150)',
          'a200': 'var(--color-beige-a200)',
        },
        // Yellow
        'yellow': {
          50: 'var(--color-yellow-50)',
          100: 'var(--color-yellow-100)',
          200: 'var(--color-yellow-200)',
          300: 'var(--color-yellow-300)',
          400: 'var(--color-yellow-400)',
          500: 'var(--color-yellow-500)',
          600: 'var(--color-yellow-600)',
          700: 'var(--color-yellow-700)',
          800: 'var(--color-yellow-800)',
          900: 'var(--color-yellow-900)',
          950: 'var(--color-yellow-950)',
        },
        // Peach
        'peach': {
          50: 'var(--color-peach-50)',
          100: 'var(--color-peach-100)',
          200: 'var(--color-peach-200)',
          300: 'var(--color-peach-300)',
          400: 'var(--color-peach-400)',
          500: 'var(--color-peach-500)',
          600: 'var(--color-peach-600)',
          700: 'var(--color-peach-700)',
          800: 'var(--color-peach-800)',
          900: 'var(--color-peach-900)',
          950: 'var(--color-peach-950)',
        },
        // Teal
        'teal': {
          50: 'var(--color-teal-50)',
          100: 'var(--color-teal-100)',
          200: 'var(--color-teal-200)',
          300: 'var(--color-teal-300)',
          400: 'var(--color-teal-400)',
          500: 'var(--color-teal-500)',
          600: 'var(--color-teal-600)',
          700: 'var(--color-teal-700)',
          800: 'var(--color-teal-800)',
          900: 'var(--color-teal-900)',
        },
        // Semantic Design System Colors
        // Interactive colors
        'interactive-background': {
          'beige-disabled': 'var(--color-interactive-background-beige-disabled)',
          'beige-highlighted': 'var(--color-interactive-background-beige-highlighted)',
          'beige-muted': 'var(--color-interactive-background-beige-muted)',
          'beige-normal': 'var(--color-interactive-background-beige-normal)',
          'beige-subtle': 'var(--color-interactive-background-beige-subtle)',
          'destructive-disabled': 'var(--color-interactive-background-destructive-disabled)',
          'destructive-highlighted': 'var(--color-interactive-background-destructive-highlighted)',
          'destructive-muted': 'var(--color-interactive-background-destructive-muted)',
          'destructive-normal': 'var(--color-interactive-background-destructive-normal)',
          'gray-disabled': 'var(--color-interactive-background-gray-disabled)',
          'gray-highlighted': 'var(--color-interactive-background-gray-highlighted)',
          'gray-intense': 'var(--color-interactive-background-gray-intense)',
          'gray-muted': 'var(--color-interactive-background-gray-muted)',
          'gray-normal': 'var(--color-interactive-background-gray-normal)',
          'white-disabled': 'var(--color-interactive-background-white-disabled)',
          'white-highlighted': 'var(--color-interactive-background-white-highlighted)',
          'white-muted': 'var(--color-interactive-background-white-muted)',
          'white-normal': 'var(--color-interactive-background-white-normal)',
          'white-transparent': 'var(--color-interactive-background-white-transparent)',
        },
        'interactive-text': {
          'beige-disabled': 'var(--color-interactive-text-beige-disabled)',
          'beige-highlighted': 'var(--color-interactive-text-beige-highlighted)',
          'beige-muted': 'var(--color-interactive-text-beige-muted)',
          'beige-normal': 'var(--color-interactive-text-beige-normal)',
          'beige-subtle': 'var(--color-interactive-text-beige-subtle)',
          'destructive-disabled': 'var(--color-interactive-text-destructive-disabled)',
          'destructive-highlighted': 'var(--color-interactive-text-destructive-highlighted)',
          'destructive-normal': 'var(--color-interactive-text-destructive-normal)',
          'gray-disabled': 'var(--color-interactive-text-gray-disabled)',
          'gray-highlighted': 'var(--color-interactive-text-gray-highlighted)',
          'gray-muted': 'var(--color-interactive-text-gray-muted)',
          'gray-normal': 'var(--color-interactive-text-gray-normal)',
          'gray-subtle': 'var(--color-interactive-text-gray-subtle)',
          'white-normal': 'var(--color-interactive-text-white-normal)',
        },
        'interactive-border': {
          'beige-disabled': 'var(--color-interactive-border-beige-disabled)',
          'beige-highlighted': 'var(--color-interactive-border-beige-highlighted)',
          'beige-intense': 'var(--color-interactive-border-beige-intense)',
          'beige-normal': 'var(--color-interactive-border-beige-normal)',
          'beige-subtle': 'var(--color-interactive-border-beige-subtle)',
          'destructive-disabled': 'var(--color-interactive-border-destructive-disabled)',
          'destructive-highlighted': 'var(--color-interactive-border-destructive-highlighted)',
          'destructive-normal': 'var(--color-interactive-border-destructive-normal)',
          'gray-disabled': 'var(--color-interactive-border-gray-disabled)',
          'gray-highlighted': 'var(--color-interactive-border-gray-highlighted)',
          'gray-intense': 'var(--color-interactive-border-gray-intense)',
          'gray-muted': 'var(--color-interactive-border-gray-muted)',
          'gray-normal': 'var(--color-interactive-border-gray-normal)',
          'gray-subtle': 'var(--color-interactive-border-gray-subtle)',
          'white-disabled': 'var(--color-interactive-border-white-disabled)',
          'white-normal': 'var(--color-interactive-border-white-normal)',
          'white-transparent': 'var(--color-interactive-border-white-transparent)',
        },
        'interactive-icon': {
          'beige-disabled': 'var(--color-interactive-icon-beige-disabled)',
          'beige-muted': 'var(--color-interactive-icon-beige-muted)',
          'beige-normal': 'var(--color-interactive-icon-beige-normal)',
          'gray-disabled': 'var(--color-interactive-icon-gray-disabled)',
          'gray-muted': 'var(--color-interactive-icon-gray-muted)',
          'gray-subtle': 'var(--color-interactive-icon-gray-subtle)',
          'white-normal': 'var(--color-interactive-icon-white-normal)',
        },
        // Surface colors
        'surface-background': {
          'beige-highlighted': 'var(--color-surface-background-beige-highlighted)',
          'beige-intense': 'var(--color-surface-background-beige-intense)',
          'beige-normal': 'var(--color-surface-background-beige-normal)',
          'beige-subtle': 'var(--color-surface-background-beige-subtle)',
          'gray-muted': 'var(--color-surface-background-gray-muted)',
          'gray-normal': 'var(--color-surface-background-gray-normal)',
          'gray-subtle': 'var(--color-surface-background-gray-subtle)',
          'peach-normal': 'var(--color-surface-background-peach-normal)',
          'peach-subtle': 'var(--color-surface-background-peach-subtle)',
          'white-normal': 'var(--color-surface-background-white-normal)',
          'white-transparent': 'var(--color-surface-background-white-transparent)',
        },
        'surface-border': {
          'beige-subtle': 'var(--color-surface-border-beige-subtle)',
          'gray-subtle': 'var(--color-surface-border-gray-subtle)',
        },
        'surface-text': {
          'gray-normal': 'var(--color-surface-text-gray-normal)',
          'gray-subtle': 'var(--color-surface-text-gray-subtle)',
        },
        // Feedback colors
        'feedback-background': {
          'information-intense': 'var(--color-feedback-background-information-intense)',
          'information-normal': 'var(--color-feedback-background-information-normal)',
          'information-subtle': 'var(--color-feedback-background-information-subtle)',
          'negative-intense': 'var(--color-feedback-background-negative-intense)',
          'negative-normal': 'var(--color-feedback-background-negative-normal)',
          'negative-subtle': 'var(--color-feedback-background-negative-subtle)',
          'neutral-clear': 'var(--color-feedback-background-neutral-clear)',
          'neutral-highlighted': 'var(--color-feedback-background-neutral-highlighted)',
          'neutral-intense': 'var(--color-feedback-background-neutral-intense)',
          'neutral-minimal': 'var(--color-feedback-background-neutral-minimal)',
          'neutral-normal': 'var(--color-feedback-background-neutral-normal)',
          'neutral-subtle': 'var(--color-feedback-background-neutral-subtle)',
          'notice-intense': 'var(--color-feedback-background-notice-intense)',
          'notice-normal': 'var(--color-feedback-background-notice-normal)',
          'notice-subtle': 'var(--color-feedback-background-notice-subtle)',
          'positive-intense': 'var(--color-feedback-background-positive-intense)',
          'positive-normal': 'var(--color-feedback-background-positive-normal)',
          'positive-subtle': 'var(--color-feedback-background-positive-subtle)',
        },
        'feedback-border': {
          'information-intense': 'var(--color-feedback-border-information-intense)',
          'information-normal': 'var(--color-feedback-border-information-normal)',
          'information-subtle': 'var(--color-feedback-border-information-subtle)',
          'negative-intense': 'var(--color-feedback-border-negative-intense)',
          'negative-normal': 'var(--color-feedback-border-negative-normal)',
          'negative-subtle': 'var(--color-feedback-border-negative-subtle)',
          'neutral-intense': 'var(--color-feedback-border-neutral-intense)',
          'neutral-normal': 'var(--color-feedback-border-neutral-normal)',
          'neutral-subtle': 'var(--color-feedback-border-neutral-subtle)',
          'notice-intense': 'var(--color-feedback-border-notice-intense)',
          'notice-normal': 'var(--color-feedback-border-notice-normal)',
          'notice-subtle': 'var(--color-feedback-border-notice-subtle)',
          'positive-intense': 'var(--color-feedback-border-positive-intense)',
          'positive-normal': 'var(--color-feedback-border-positive-normal)',
          'positive-subtle': 'var(--color-feedback-border-positive-subtle)',
        },
        'feedback-text': {
          'information-intense': 'var(--color-feedback-text-information-intense)',
          'information-subtle': 'var(--color-feedback-text-information-subtle)',
          'negative-intense': 'var(--color-feedback-text-negative-intense)',
          'negative-subtle': 'var(--color-feedback-text-negative-subtle)',
          'neutral-minimal': 'var(--color-feedback-text-neutral-minimal)',
          'neutral-muted': 'var(--color-feedback-text-neutral-muted)',
          'neutral-normal': 'var(--color-feedback-text-neutral-normal)',
          'neutral-subtle': 'var(--color-feedback-text-neutral-subtle)',
          'notice-intense': 'var(--color-feedback-text-notice-intense)',
          'notice-subtle': 'var(--color-feedback-text-notice-subtle)',
          'positive-intense': 'var(--color-feedback-text-positive-intense)',
          'positive-subtle': 'var(--color-feedback-text-positive-subtle)',
        },
        // Popup colors
        'popup-background': {
          'normal': 'var(--color-popup-background-normal)',
          'subtle': 'var(--color-popup-background-subtle)',
        },
        'popup-text': {
          'intense': 'var(--color-popup-text-intense)',
          'muted': 'var(--color-popup-text-muted)',
          'normal': 'var(--color-popup-text-normal)',
        },
        // Overlay colors
        'overlay-background': {
          'subtle': 'var(--color-overlay-background-subtle)',
        },
        // Sidebar semantic colors
        'sidebar': 'hsl(var(--sidebar))',
        'sidebar-foreground': 'hsl(var(--sidebar-foreground))',
        'sidebar-primary': 'hsl(var(--sidebar-primary))',
        'sidebar-primary-foreground': 'hsl(var(--sidebar-primary-foreground))',
        'sidebar-accent': 'hsl(var(--sidebar-accent))',
        'sidebar-accent-foreground': 'hsl(var(--sidebar-accent-foreground))',
        'sidebar-border': 'hsl(var(--sidebar-border))',
        'sidebar-ring': 'hsl(var(--sidebar-ring))',
        // Other utility colors
        'background': 'hsl(var(--background))',
        'popover': 'hsl(var(--popover))',
        'popover-foreground': 'hsl(var(--popover-foreground))',
      },
      borderRadius: {
        'none': 'var(--radius-none)',
        'sm': 'var(--radius-sm)',
        'md': 'var(--radius-md)',
        'lg': 'var(--radius-lg)',
        'xl': 'var(--radius-xl)',
        'full': 'var(--radius-full)',
        // Plum specific radius
        '0': 'var(--radius-0)',
        '05': 'var(--radius-05)',
        '1': 'var(--radius-1)',
        '15': 'var(--radius-15)',
        '2': 'var(--radius-2)',
        '25': 'var(--radius-25)',
        '3': 'var(--radius-3)',
        '4': 'var(--radius-4)',
        '6': 'var(--radius-6)',
        '8': 'var(--radius-8)',
      },
      fontFamily: {
        'primary': ['var(--font-family-primary)', 'sans-serif'],
        'secondary': ['var(--font-family-secondary)', 'sans-serif'],
      },
      fontSize: {
        'xs': ['var(--font-size-xs)', { lineHeight: 'var(--line-height-xs)' }],
        'sm': ['var(--font-size-sm)', { lineHeight: 'var(--line-height-sm)' }],
        'base': ['var(--font-size-base)', { lineHeight: 'var(--line-height-base)' }],
        'lg': ['var(--font-size-lg)', { lineHeight: 'var(--line-height-lg)' }],
        'xl': ['var(--font-size-xl)', { lineHeight: 'var(--line-height-xl)' }],
        '2xl': ['var(--font-size-2xl)', { lineHeight: 'var(--line-height-2xl)' }],
        '3xl': ['var(--font-size-3xl)', { lineHeight: 'var(--line-height-3xl)' }],
        '4xl': ['var(--font-size-4xl)', { lineHeight: 'var(--line-height-4xl)' }],
      },
      spacing: {
        '1': 'var(--spacing-1)',
        '2': 'var(--spacing-2)',
        '3': 'var(--spacing-3)',
        '4': 'var(--spacing-4)',
        '5': 'var(--spacing-5)',
        '6': 'var(--spacing-6)',
        '8': 'var(--spacing-8)',
        '10': 'var(--spacing-10)',
        '12': 'var(--spacing-12)',
        '16': 'var(--spacing-16)',
        // Custom spacing from your current system
        '05': '2px',
        '25': '10px',
        '15': '3.75rem',
        '18': '4.5rem',
        '60': '15rem',
        '64': '16rem',
        '80': '20rem',
        '90': '22.5rem',
        '100': '25rem',
        '106': '26.5rem',
        '112': '28rem',
        '120': '30rem',
        '140': '35rem',
        '150': '37.5rem',
        '160': '40rem',
        '200': '50rem',
      },
      maxHeight: {
        '90': '22.5rem',
        '120': '30rem',
        '140': '35rem',
        '160': '40rem',
        '320': '320px',
      },
      height: {
        '05': '2px',
        '25': '10px',
        '18': '72px',
        '32': '128px',
        '37': '148px',
      },
      width: {
        '05': '2px',
        '25': '10px',
        '15': '3.75rem',
        '18': '4.5rem',
        '60': '15rem',
        '64': '16rem',
        '80': '20rem',
        '100': '25rem',
        '106': '26.5rem',
        '112': '28rem',
        '120': '30rem',
        '150': '37.5rem',
        '200': '50rem',
      },
      zIndex: {
        '1': '1',
        '10': '10',
        '20': '20',
        '50': '50',
      },
      inset: {
        '10-negative': '-40px',
        '8-negative': '-8px',
        '3-negative': '-12px',
      },
      // Add custom utilities for missing classes
      margin: {
        '3-negative': '-12px',
      },
      translate: {
        'x-1/2': '-50%',
        'y-1/2': '-50%',
      },
      animation: {
        'smart': 'all 300ms linear',
        'smart-opacity': 'opacity 300ms linear',
        'smart-transform': 'transform 300ms linear',
        'smart-colors': 'fill 300ms linear, stroke 300ms linear',
        'smart-layout': 'width 300ms linear, height 300ms linear, padding 300ms linear, margin 300ms linear',
        'smart-position': 'top 300ms linear, left 300ms linear, right 300ms linear, bottom 300ms linear',
      }
    },
  },
  plugins: [],
  // Enable arbitrary value support and ensure all semantic classes are included
  safelist: [
    // Include all semantic design system classes
    {
      pattern: /bg-(interactive|surface|feedback|popup|overlay)-/,
    },
    {
      pattern: /text-(interactive|surface|feedback|popup)-/,
    },
    {
      pattern: /border-(interactive|surface|feedback)-/,
    },
    {
      pattern: /fill-(interactive)-/,
    },
    // Animation classes
    {
      pattern: /animate-smart/,
    },
    // Sidebar semantic classes
    {
      pattern: /sidebar/,
    },
    // Focus utility classes
    'plum-focus',
    'focus-visible:plum-focus',
    // Position utilities
    'left-full',
    'top-50',
    // Z-index utilities
    'z-50',
    'z-20',
    'z-10',
    // Negative margins
    'ml-3-negative',
    // Missing basic utilities
    'w-fit',
    'h-fit',
    'min-h-svh',
    'overflow-ellipsis',
  ],
}
