import { Drawer as DrawerPrimitive } from 'vaul';
import { DrawerType, SideDrawerStyle } from './types';
import * as React from "react";
declare function Drawer({ ...props }: React.ComponentProps<typeof DrawerPrimitive.Root>): import("react/jsx-runtime").JSX.Element;
declare function DrawerTrigger({ ...props }: React.ComponentProps<typeof DrawerPrimitive.Trigger>): import("react/jsx-runtime").JSX.Element;
declare function DrawerContent({ className, children, title, buttonLabel, sideDrawerStyle, type, bodyContent, sideDrawerHeading, sideDrawerDescription, showCloseButton, currentRecord, totalRecords, recordType, leadingContent, trailingContent, tertiaryButtonLabel, tertiaryButtonOnClick, primaryButtonLabel, primaryButtonOnClick, sideDrawerHeadingButtonClick, onSideDrawerLinkButtonClick, getPreviousRecord, getNextRecord, showNotification, showSearchButton, onSearchButtonClick, showDivider1, showDivider2, ...props }: React.ComponentProps<typeof DrawerPrimitive.Content> & {
    type?: DrawerType;
    title?: string;
    buttonLabel?: string;
    sideDrawerStyle: SideDrawerStyle;
    bodyContent: React.ReactNode;
    sideDrawerHeading: string;
    sideDrawerDescription: string;
    showCloseButton: boolean;
    currentRecord: number;
    totalRecords: number;
    recordType: string;
    leadingContent: React.ReactNode;
    trailingContent: React.ReactNode;
    tertiaryButtonLabel?: string;
    tertiaryButtonOnClick?: () => void;
    primaryButtonLabel?: string;
    primaryButtonOnClick?: () => void;
    sideDrawerHeadingButtonClick?: () => void;
    onSideDrawerLinkButtonClick?: () => void;
    getPreviousRecord?: () => void;
    getNextRecord?: () => void;
    showNotification?: boolean;
    showSearchButton?: boolean;
    onSearchButtonClick?: () => void;
    showDivider1?: boolean;
    showDivider2?: boolean;
}): import("react/jsx-runtime").JSX.Element;
export { Drawer, DrawerTrigger, DrawerContent, };
