import { default as DownloadIcon } from './downloadIcon';
import { default as LoadingIcon } from './loadingIcon';
import { default as InfoIcon } from './infoIcon';
import { default as CrossCloseIcon } from './crossCloseIcon';
import { default as RightArrowIcon } from './rightArrowIcon';
import { default as RoundedAddIcon } from './roundedAddIcon';
import { default as SearchIcon } from './searchIcon';
import { default as CommandKeyIcon } from './commandKeyIcon';
import { default as CalendarIcon } from './calendarIcon';
import { default as ErrorIndicationIcon } from './ErrorIndicationIcon';
import { default as SuccessIndicationIcon } from './SuccessIndicationIcon';
import { default as CheckedIcon } from './checkedIcon';
import { default as SuccessIndicationFilledIcon } from './SuccessIndicationFilledIcon';
import { default as ErrorIndicationFilledIcon } from './ErrorIndicationFilledIcon';
import { default as InfoIconFilled } from './infoIconFilled';
import { default as DotIcon } from './DotIcon';
import { default as CircleIcon } from './circleIcon';
import { default as CircleDotIcon } from './circleDotIcon';
import { default as ChevronRight } from './chevronRight';
import { default as FilterIcon } from './FilterIcon';
import { default as ChevronDown } from './ChevronDown';
import { default as TooltipArrow } from './tooltipArrow';
import { default as HeartIcon } from './heartIcon';
import { default as ListTreeIcon } from './ListTreeIcon';
import { default as UserIcon } from './userIcon';
import { default as SquareIcon } from './squareIcon';
import { default as SquareCheckIcon } from './squareCheckIcon';
import { default as TrashIcon } from './trashIcon';
import { default as SquareMinusIcon } from './squareMinusIcon';
import { default as UserXIcon } from './userXIcon';
import { default as CircleCheckFilledIcon } from './circleCheckFilled';
import { default as AlertFilledIcon } from './alertFilledIcon';
import { default as SlashIcon } from './slashIcon';
import { default as EllipsisIcon } from './ellipsis';
import { default as LeftChevronIcon } from './leftChevronIcon';
import { default as AlertIcon } from './AlertIcon';
import { default as LeftArrowIcon } from './leftArrowIcon';
import { default as HomeIcon } from './homeIcon';
import { default as StarIcon } from './starIcon';
import { default as IndianRupee } from './inidanRupee';
import { default as EndorsementsIcon } from './endorsementsIcon';
import { default as FileText } from './fileText';
import { default as GraduationCapIcon } from './graduationCapIcon';
import { default as MessageQuestionIcon } from './messageQuestionIcon';
import { default as SettingsIcon } from './settingsIcon';
import { default as ChevronUp } from './ChevronUp';
import { default as EllipsisVerticalIcon } from './ellipsisVertical';
import { default as LogoutIcon } from './logoutIcon';
export type IIconProps = {
    color?: string;
    className?: string;
    size?: string;
    disabled?: boolean;
};
export { DownloadIcon, LoadingIcon, InfoIcon, CrossCloseIcon, RightArrowIcon, RoundedAddIcon, SearchIcon, CommandKeyIcon, CalendarIcon, ErrorIndicationIcon, SuccessIndicationIcon, CheckedIcon, SuccessIndicationFilledIcon, ErrorIndicationFilledIcon, InfoIconFilled, DotIcon, CircleIcon, CircleDotIcon, ChevronRight, FilterIcon, ChevronDown, TooltipArrow, HeartIcon, ListTreeIcon, UserIcon, SquareIcon, SquareCheckIcon, TrashIcon, SquareMinusIcon, UserXIcon, CircleCheckFilledIcon, AlertFilledIcon, ChevronDownIcon, TooltipArrowIcon, SlashIcon, EllipsisIcon, LeftChevronIcon, AlertIcon, LeftArrowIcon, HomeIcon, StarIcon, IndianRupee, EndorsementsIcon, FileText, GraduationCapIcon, MessageQuestionIcon, SettingsIcon, ChevronUp, EllipsisVerticalIcon, LogoutIcon, };
